trigger:
- Development

name: Deploy Bicep files

variables:
  azureServiceConnection: 'AzureConnection_huisman-general-d-001'
  resourceGroupName: 'rg-weu-jzaal-0451-d-001'
  location: 'westeurope'

pool: MyPool


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)/main.bicep